# Generated by Django 3.2.5 on 2021-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20211019_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
