# Generated by Django 3.2.5 on 2021-10-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_dashboard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pindicator',
            name='valueType',
            field=models.CharField(default='abs', max_length=100),
        ),
    ]
